### ISSUE TITLE
gtsam_unstable IncrementalFixedLagSmoother.h vtable error

### ISSUE THREAD

**Issue by epicjung** [borglab/gtsam#837] opened 2021-08-02 10:00 UTC
## Description
Hi, I am trying to use "IncrementalFixedLagSmoother" in the GTSAM unstable. The compile error occurs when I compile a c++ program as follows: 
**Version 1:**

```cpp
void optimization::optimize()
{
  double lag = 10.0;
  ISAM2Params params; 
  params.relinearizeThreshold = 0.1;
  params.relinearizeSkip = 1;
  gtsam::IncrementalFixedLagSmoother smoother(lag, params);
}
```

**Version 2:** (This compiles fine)
```cpp
void optimization::optimize()
{
  double lag = 10.0;
  ISAM2Params params; 
  params.relinearizeThreshold = 0.1;
  params.relinearizeSkip = 1;
  gtsam::IncrementalFixedLagSmoother smoother();
}
```

The version 2 works fine, where there are no parameters in the constructor. However, when I input parameters as in Version 1, the terminal shows something like this:

```bash
CMakeFiles/sensor_fusion_optimization.dir/src/optimization.cpp.o: In function `optimization::optimize()':
/usr/local/include/gtsam_unstable/nonlinear/IncrementalFixedLagSmoother.h:43: undefined reference to `vtable for gtsam::IncrementalFixedLagSmoother'
CMakeFiles/sensor_fusion_optimization.dir/src/optimization.cpp.o: In function `optimization::optimize()':
/usr/local/include/gtsam_unstable/nonlinear/FixedLagSmoother.h:69: undefined reference to `vtable for gtsam::FixedLagSmoother'
CMakeFiles/sensor_fusion_optimization.dir/src/optimization.cpp.o: In function `gtsam::IncrementalFixedLagSmoother::~IncrementalFixedLagSmoother()':
/usr/local/include/gtsam_unstable/nonlinear/IncrementalFixedLagSmoother.h:47: undefined reference to `vtable for gtsam::IncrementalFixedLagSmoother'
CMakeFiles/sensor_fusion_optimization.dir/src/optimization.cpp.o: In function `gtsam::IncrementalFixedLagSmoother::~IncrementalFixedLagSmoother()':
/usr/local/include/gtsam_unstable/nonlinear/FixedLagSmoother.h:69: undefined reference to `vtable for gtsam::FixedLagSmoother'
CMakeFiles/sensor_fusion_optimization.dir/src/optimization.cpp.o: In function `gtsam::IncrementalFixedLagSmoother::~IncrementalFixedLagSmoother()':
/usr/local/include/gtsam_unstable/nonlinear/IncrementalFixedLagSmoother.h:47: undefined reference to `vtable for gtsam::IncrementalFixedLagSmoother'
CMakeFiles/sensor_fusion_optimization.dir/src/optimization.cpp.o: In function `gtsam::IncrementalFixedLagSmoother::~IncrementalFixedLagSmoother()':
/usr/local/include/gtsam_unstable/nonlinear/FixedLagSmoother.h:69: undefined reference to `vtable for gtsam::FixedLagSmoother'
collect2: error: ld returned 1 exit status
sensor_fusion/CMakeFiles/sensor_fusion_optimization.dir/build.make:808: recipe for target '/home/euigon/fusion_ros/devel/lib/sensor_fusion/sensor_fusion_optimization' failed
make[2]: *** [/home/euigon/fusion_ros/devel/lib/sensor_fusion/sensor_fusion_optimization] Error 1
CMakeFiles/Makefile2:1151: recipe for target 'sensor_fusion/CMakeFiles/sensor_fusion_optimization.dir/all' failed
make[1]: *** [sensor_fusion/CMakeFiles/sensor_fusion_optimization.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I couldn't find any post regarding this error. I appreciate if you could help me on this.

## Steps to reproduce

1. 
2.

## Environment
C++, Ubuntu 18.04, GTSAM "develop" branch

**Comment by varunagrawal** [comment] 2021-08-20 05:02
@epicjung can you please provide a minimal reproducible example? Just the code snippets provided don't give us sufficient info, a full example would be much more insightful.

**Comment by Binbin418916** [comment] 2021-11-24 03:20
add `gtsam_unstable` in target_link_libraries, 
like
target_link_libraries(exe_file
    gtsam
    gtsam_unstable
)

**Comment by dellaert** [comment] 2021-12-22 17:00
@Binbin418916 Small PR?

**Comment by Williamwenda** [comment] 2022-01-13 03:51
> add `gtsam_unstable` in target_link_libraries, like target_link_libraries(exe_file gtsam gtsam_unstable )

This solution works out

**Comment by varunagrawal** [comment] 2022-01-13 21:39
From the comments it seems that the author was not linking gtsam_unstable correctly in their project. Since a solution has been reached and there is no need for a PR, we're closing this.

**Closed** 2022-01-13 21:40 UTC
Labels: bug

**Comment by RomanStadlhuber** [comment] 2024-12-08 23:51
@varunagrawal When installing from [`ros-noetic-gtsam`](https://index.ros.org/p/gtsam/github-borglab-gtsam/#noetic), I cannot do this, i.e. adding

```cmake
find_package(GTSAM REQUIRED)

add_library(xyz xyz.cxx)

target_link_libraries(xyz
  gtsam
  gtsam_unstable
)
```

and then `cmake --build ../build`  I get

```bash
[build] /usr/bin/ld: cannot find -lgtsam_unstable
```

I am using CMake v. 3.16.3 from ROS Noetic on Ubuntu 20.04.

When omitting `gtsam_unstable` stuff in my source code and the respective library in CMakeLists.txt, linking to regular gtsam works just fine.
Is there something I am missing?

**Comment by varunagrawal** [comment] 2024-12-09 22:02
@RomanStadlhuber how are you installing GTSAM? From source or from the ubuntu package?

**Comment by RomanStadlhuber** [comment] 2024-12-09 22:23
@varunagrawal I have installed it from the ubuntu package with `apt install ros-noetic-gtsam`.

I have found out in the meantime, that I also needed to add `find_package(GTSAM_UNSTABLE REQUIRED)` in order to make it work.

**Comment by varunagrawal** [comment] 2024-12-09 22:40
Yup, `find_package(GTSAM_UNSTABLE REQUIRED)` should do it for you. Glad you managed to fix it.
