### ISSUE TITLE
It was found that the system would crash if there were more than 5000 nodes under Windows.

### ISSUE THREAD

**Issue by hunkyu** [borglab/gtsam#1826] opened 2024-09-07 08:20 UTC
![image](https://github.com/user-attachments/assets/a9a05eda-3d8e-44eb-a3b0-a5603d53bee8)

**Comment by hunkyu** [comment] 2024-09-07 08:21
Use the official demo

**Comment by ProfFan** [comment] 2024-09-07 13:58
Please change your default stack size and report if that fix it?

**Comment by luyuanxunnuli** [comment] 2024-09-10 02:51
> Please change your default stack size and report if that fix it?

Thank you for your reply. I have set the stack size of gtsam.dll and  programs which use gtsam.dll to 10M and 100M, but it crashes too.It is the same issue as #1827, #1827 is more detailed.

**Comment by ProfFan** [comment] 2024-09-10 14:30
Many thanks @luyuanxunnuli ! I'll close this one as duplicate of #1827.

**Closed as completed by ProfFan** 2024-09-10 14:30 UTC

**Comment by hunkyu** [comment] 2024-09-11 04:01
@ProfFan Setting the stack reserve size based on the VS software does not work
