### ISSUE TITLE
"matlab/gtsam_examples/IMUKittiExampleGPS"  fails to run!

### ISSUE THREAD

**Issue by solution3000** [borglab/gtsam#523] opened 2020-09-14 08:11 UTC
![image](https://user-images.githubusercontent.com/20204121/93060127-4b807280-f6a4-11ea-9ea8-292e822707b6.png)

https://github.com/jlblancoc/2020-ual-factor-graphs-course is the matlab toolbox!

**Comment by varunagrawal** [comment] 2021-01-03 18:20
@jlblancoc can you please look at this? Thanks!

**Comment by ProfFan** [comment] 2021-01-03 20:23
Can this be reproduced under Linux? Seems to be an RTTI issue.

**Comment by mattking-smith** [comment] 2021-12-22 18:16
Is this still an open issue? 

I have the current wrap library + GTSAM toolbox on in a Ubuntu 20.04 environment with MATLAB 2021a and I have no issues with this example. 

@solution3000 Can you try wrapping the current GTSAM environment into MATLAB and verify it works on your machine?

**Comment by varunagrawal** [comment] 2021-12-22 18:30
I think this can be marked as resolved. @solution3000 if you still have issues, you can just reopen this issue and provide more details. :slightly_smiling_face:

**Closed by varunagrawal** 2021-12-22 18:30 UTC
Labels: matlab
